###
# Teste da rota POST /reserva (Criar reserva)
POST http://localhost:3000/reserva
Content-Type: application/json

{
  "usuario_id": 1,
  "sala_id": 2,
  "data_checkin": "2025-06-01",
  "data_checkout": "2025-06-02",
  "status": "pendente"
}

###
# Teste da rota GET /reserva (Listar reservas)
GET http://localhost:3000/reserva
Accept: application/json

###
# Teste da rota PUT /reserva/:id (Editar reserva)
PUT http://localhost:3000/reserva/1
Content-Type: application/json

{
  "usuario_id": 1,
  "sala_id": 3,
  "data_checkin": "2025-06-03",
  "data_checkout": "2025-06-04",
  "status": "confirmada"
}

###
# Teste da rota PATCH /reserva/:id/status (Atualizar só o status)
PATCH http://localhost:3000/reserva/1/status
Content-Type: application/json

{
  "status": "cancelada"
}

###
# Teste da rota DELETE /reserva/:id (Excluir reserva)
DELETE http://localhost:3000/reserva/1
Accept: application/json
